### ISSUE TITLE
GetRecords throw an exception when using a record type

### ISSUE THREAD

**Issue by thestonehead** [MarkPflug/Sylvan#141]
Hi.

This is the example:
`csvReader.GetRecords<FileImportItem>()`

`public record class FileImportItem 
    {
        public long Id { get; set; }
       ...
    }`

Throws UnboundMemberException.

It doesn't when it's a normal class or a "record struct". I can work around it with structs, but I wanted to report it here so you can fix it if you want.

**Comment by MarkPflug** [comment]
Interesting. I've yet to use the record class/struct feature of C#. It appears the issue is that there is a compiler generated property `Type EqualityContract` on the record class that the binder wants to bind a value to. The property doesn't have a setter though, so that is definitely a bug that needs to be fixed.

You can work around this pretty easily. The `GetRecords<T>` is essentially just a helper extension method that makes the binder easy to use providing the default settings. You can implement your own extension (or use the binder directly) to have more control over the binder behavior. Specifically, there is a property on the binder named `BindingMode` that controls whether all columns/properties must be bound. By default, it uses `AllProperties` mode, meaning that all properties on the target type need to have a value bound to them from the source data. You can change this to use `AllColumn` to require that all columns are bound to a property, or `Any` which is the most lenient, and doesn't really validate the columns/properties.

Here is what such an extension would look like:
```C#
static class DataExtensions
{
    public static IEnumerable<T> GetRecords<T>(this DbDataReader reader)
        where T : class, new()
    {
        var opts = new DataBinderOptions { BindingMode = DataBindingMode.AllColumns };
        var binder = DataBinder.Create<T>(reader, opts);
        while (reader.Read())
        {
            var item = new T();
            binder.Bind(reader, item);
            yield return item;
        }
    }
}
```
You would use it exactly like the `GetRecords` in Sylvan.Data.

You mentioned `record struct` working correctly. Unfortunatley, that is another bug I need to fix. Binding to structs (or record structs) doesn't work, and the values on the struct will all end up with their default value. This was meant to be an unsupported scenario, but apparently I forgot to add the constraints to prevent it. The `class` constraint in the code above is missing in the Sylvan.Data code.

**Comment by MarkPflug** [comment]
Thanks for bringing this issue to my attention. I just pushed https://www.nuget.org/packages/Sylvan.Data/0.2.3 to fix both the `record class` binder issue, and added the class constraint.

**Comment by thestonehead** [comment]
Fantastic! :)

**Comment by MarkPflug** [comment]
If you've found the library to be useful, please give the repository a star. Helps other people discover it.
