### ISSUE TITLE
A 19kb record throws CsvRecordTooLargeException

### ISSUE THREAD

**Issue by ohtwadi** [MarkPflug/Sylvan#217]
Hi,

A record in my CSV is failing with CsvRecordTooLargeException
```
Sylvan.Data.Csv.CsvRecordTooLargeException: Exception of type 'Sylvan.Data.Csv.CsvRecordTooLargeException' was thrown.
   at Sylvan.Data.Csv.CsvDataReader.NextRecordAsync(CancellationToken cancel)
   at Sylvan.Data.Csv.CsvDataReader.InitializeReaderAsync(CancellationToken cancel)
   at Sylvan.Data.Csv.CsvDataReader.InitializeReader()
   at Sylvan.Data.Csv.CsvDataReader.CreateInternal(TextReader reader, Char[] buffer, CsvDataReaderOptions options)
```

Putting the record in question in its own file tells me the record is only 19kb.  If I reduce the column data in this record to under 9kb, the error disappears. My code is straight forward.

```c#
using var dr = CsvDataReader.Create(file.FullName);
foreach (var record in dr.GetRecords<MyClass>())
```

Am I running into a buffer limit per record or a column in a record? I'm not sure how to debug this further and would appreciate any assistance.

**Comment by MarkPflug** [comment]
The default buffer size is 16k. You can set the `MaxBufferSize` to allow the buffer to grow to accommodate larger records.

```
var opts = new CsvDataReaderOptions { MaxBufferSize = int.MaxValue};
using var dr = CsvDataReader.Create(file.FullName, opts);
foreach (var record in dr.GetRecords<MyClass>())
```
This will allow the reader to potentially process records up to 2GB.

**Comment by picasso566** [comment]
@MarkPflug  Don't know where else to thank you.

Client requested a data export of their database. Certain columns are MB big with pasted html formatted text (**hence this Issue**).  I've been importing/exporting csv files since... SQL Server 7? and I swear all of the usual tools are either getting worse and I could not produce the output I desired.   

Your library successfully handles large text fields which may contain commas, line breaks, or quoted text and doesn't unnecessarily quote all of the non-string columns! I tried PS:Export-Csv, bcp, CSVHelper, FileHelpers, SSIS, SQL Exports, and on and on. 
 
From this list: [fastest-net-csv-parsers](https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers) I started going through libraries one by one. I didn't need a parser, just a writer. I spent 2 days trying to get this simple task done and when I switched to your library, it was done in about 2 hours. 

I've seen your projects for years, but never tried them. Glad I did! Thank you so much for this library.

**Comment by MarkPflug** [comment]
@picasso566 Thanks for the kind words! Glad you've found the library useful.

**Comment by loop-evgeny** [comment]
Thank you @MarkPflug , both for the library and for this helpful comment that allowed me to fix the issue quickly!

It would be nice to improve the exception message, however. Right now it's just "Exception of type 'Sylvan.Data.Csv.CsvRecordTooLargeException' was thrown.". It would be nice to say that a row failed to be parsed because the buffer was too small, include the row number (which I see is stored in the exception already) and even tell the user in the message how to fix the problem.

The whole MaxBufferSize is a bit of a gotcha, though. I don't know the code, so I don't know why it uses this buffer, but the entire row that failed to be parsed was only 1554 characters in my case. Why would that fail to be parsed with a 16 KB buffer?
