### ISSUE TITLE
Sylvan CSV - ResultSetMode on "non-standard" csv files

### ISSUE THREAD

**Issue by niko86** [MarkPflug/Sylvan#79]
Hello,
This is not particularly an issue with your code but rather the particular file format that I am using which doesn't play nicely.

The file format is effectively multiple CSV tables in a single file and the number of headings will vary. A basic example is below:

```
"TABLE","TABLENAME1"
"HEADINGROW","HEADING_1","HEADING_2","HEADING_3","HEADING_4"
"DATAROW","DATA_1.1","DATA_1.2","DATA_1.3","DATA_1.4"
"DATAROW","DATA_2.1","DATA_2.2","DATA_2.3","DATA_2.4"

"TABLE","TABLENAME2"
"HEADINGROW","HEADING_X","HEADING_Y"
"DATAROW","DATA_X.1","DATA_Y.2"
"DATAROW","DATA_X.1","DATA_Y.2"
```

If I set ResultSetMode to SingleResult when I call GetValues and assign it to an array I only get the first two columns with values and the others column values are null. If i use a for loop on the RowFieldCount and calling GetString() I can retrieve all values. Using linqpad with the linked [gist ](https://gist.github.com/niko86/ba2c4f2e8b6f8bac4003b83a386ac8ae) i get the below output:

```
====== First Row ======
-- Row Field Count For Loop Start
TABLE
TABLENAME1
-- Row Field Count For Loop End
-- Field Count For Loop Start
TABLE
TABLENAME1
-- Field Count For Loop End
====== Second Row ======
-- Row Field Count For Loop Start
HEADINGROW
HEADING_1
HEADING_2
HEADING_3
HEADING_4
-- Row Field Count For Loop End
-- Field Count For Loop Start
HEADINGROW
HEADING_1
-- Field Count For Loop End
```

Conversely if i set to MultiResult once it goes from row 1 with two columns to row 2 with more columns i can't retrieve any values in a for loop using RowFieldCount and only blank values using FieldCount as shown with the below linqpad output but set to multiresult.

```
====== First Row ======
-- Row Field Count For Loop Start
TABLE
TABLENAME1
-- Row Field Count For Loop End
-- Field Count For Loop Start
TABLE
TABLENAME1
-- Field Count For Loop End
====== Second Row ======
-- Row Field Count For Loop Start
-- Row Field Count For Loop End
-- Field Count For Loop Start


-- Field Count For Loop End
```

Hopefully the above makes sense. And finally getting to my point, am i doing something wrong in the above that i could improve? Or could some adjustment be made to accommodate for such a file format?

Thanks

**Comment by MarkPflug** [comment]
Hi @niko86, I'll take a look to see if there is some solution to this. One problem I'm seeing though, is that the way multi result reading works is that it detects result set transitions based on the number of columns in the row. The table header (`"TABLE","TABLENAME1"`) in your example has two columns. If the table data also had two columns there would be no way for my library to detect that "TABLE","TABLENAME1" wasn't the column headers for the following data. I don't see any good way to solve this particular issue. However, if your data is always guaranteed to have more than two columns, then it should be possible to make this work.

Briefly looking at the behavior it looks like there might be a flaw in the way the multi result set behavior is currently working. It looks like it might be expecting that there is always at least one row in the result set, so the table column headers row (multi column) are being included with the table name row (2 column). I'll have to do some experimentation to see if this can be fixed, which might take a few days for me to find time to investigate.

My expected behavior is that this should be interpreted as the following:

Result set 1: 2 columns, 0 rows. Headers: "TABLE", "TABLENAME1"
Result set 2: 5 columns, 2 rows. Headers: "HEADINGROW", ...
Result set 3: 2 columns, 0 rows. Headers: "TABLE", "TABLENAME2"
Result set 4: 3 columns, 2 rows. Headers: "HEADINGROW", ...

It doesn't currently appear to behave this way though, which I would consider a bug, so I'll take a look. Thanks for the good explanation and examples.

**Comment by MarkPflug** [comment]
@niko86 I just published [1.1.8-b0001](https://www.nuget.org/packages/Sylvan.Data.Csv/1.1.8-b0001) with a fix. It will now behave as I described above. Let me know if it works for you. 

The issue still exists where if the data set contains two columns it will be indistinguishable from the table header. That is something I will be unable to fix, as I don't see a reasonable solution that isn't specific to the unique shape of your files. You might be able to handle it yourself though:

```
var opts = new CsvDataReaderOptions
{
	ResultSetMode = ResultSetMode.MultiResult,
	// disable reading the column headers, your code will handle that manually.
	HasHeaders = false,
};
var csv = CsvDataReader.Create("Data/Issue_79.csv", opts);

static string[] GetHeaders(CsvDataReader csv)
{
	var headers = new string[csv.FieldCount];
	for(int i = 0; i < csv.FieldCount; i++)
	{
		headers[i] = csv.GetString(i);
	}
	return headers;
}

do
{
	string[] headers;
	if (csv.FieldCount == 2)
	{
		// skip the table header row ("TABLE","TABLENAME#")
		csv.Read();
		if (csv.Read())
		{
			// if another row was read in this result set, it is the column headers for a 2 column data set.
			headers = GetHeaders(csv);
		}
	} 
	else
	{
		csv.Read();
		headers = GetHeaders(csv);
	}

	while (csv.Read())
	{
		// process data normally, use headers array to locate data
	}

} while (csv.NextResult());
```

This is a bit of a hack, but that's the best I can offer as a workaround.

I will push an official `1.1.8` release in the next week or so that includes this fix. Until then give the pre-release package a try.

**Comment by niko86** [comment]
Thanks Mark, I will try this out. Some tables will have 2 columns but i will try to resolve it in my code. Starred the repo 👍

**Comment by MarkPflug** [comment]
> RowFieldCount obviously can see there are additional fields but the get methods are blind to these.

The field accessors (GetString, GetInt32, etc) should all be able to access any field in the row, even if RowFieldCount is greater than FieldCount. It used to be impossible to access these fields, but I changed that behavior at some point. If you are finding that doesn't work, can you put together a tight repro in a new issue and I can take a look. I tested that it works on my machine at least.
